// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_slider: dynamic(() => import("./BlogSlider")),
  hero: dynamic(() => import("./Hero")),
  living_room: dynamic(() => import("./LivingRoom")),
  table: dynamic(() => import("./Table")),
};
